### ISSUE TITLE
Monetization

### ISSUE THREAD

**Issue by Tickthokk** [CraftingAsAService/CaaS#4]
An epic to capture all of the Monetization aspects.

Create Tickets
- [x] Business Plan
  - [ ] Subscription or Donation?
  - [ ] What to Charge?
  - [ ] Avoid Paypal
      - Use Stripe?
      - Other alternatives?
- [x] Define benefits
  - Likewise, define Free stuff
- [ ] Ads?
  - Don't like the idea, but consider it
- [ ] Security & Backups very important for a paid service
  - [ ] HTTPS
  - [ ] Research Off-Server Backup Utilities
  - Uptime also important
